// GET                 => JAB SERVER SE DATA FATCH KERWANA HAI TAB ISS METHOD KA USED KERTE HAI
// POST                => SERVER PER DATA SAND KERNA HAI TAB 
// PUT/PATCH           => JAB DATA PAHLE SE HAI AUR USME KUCH UPDATE KERNA HAI TAB YE METHOD KA USED KERTE HAI 
// DELETE              => SERVER PER KOI DATA HAI OR USKO DELETE KERNA HAI TAB ISS MTHOD KA USED KERTE HAI

